spring:
  datasource:
    url: jdbc:mysql://localhost:3307/personal_site_db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}

    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:DB-init.sql"
logging:
  level:
    org.springframework.jdbc.core: DEBUG # SQL

